### ISSUE TITLE
osx plugin not detecting devices

### ISSUE THREAD

**Issue by jBernz** [WootingKb/wooting-analog-plugin#4]
I'm using a wooting one on osx. I am able to initialize the sdk wrapper but connected devices is returning 0. However, the rgb sdk is able to detect my keyboard so I imagine something is up with the analog plugin.

**Comment by PastaJ36** [comment]
~~It should work out of the box on osx. Are you on the beta firmware? We're releasing the analog SDK firmware to public next week.~~

Edit: new firmware is now live, please download the latest wootility version [here](https://wooting.io/wootility)

**Comment by jBernz** [comment]
so the latest release for osx includes a plugin called libwooting_analog_test_plugin.dylib that wasn't working. When I switched it out for the plugin installed by wootility it started working.

**Comment by simon-wh** [comment]
For future reference, the `libwooting_analog_test_plugin.dylib` is for internal SDK testing as well as the Virtual Keyboard extension. For Wooting devices to work, this plugin, the `libwooting_analog_plugin.dylib` is required
